# Generated by Django 4.0.1 on 2022-02-03 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(default=models.DateTimeField(auto_now_add=True))),
                ('status', models.BooleanField(default=True)),
                ('amount', models.IntegerField()),
                ('payement_due', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(default=models.DateTimeField(auto_now_add=True))),
                ('existing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(default=models.DateTimeField(auto_now_add=True))),
                ('attendees', models.IntegerField(default=0)),
                ('event_date', models.DateTimeField(default=models.DateTimeField(auto_now_add=True))),
                ('note', models.CharField(max_length=1024)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.customer')),
                ('event_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.contract')),
            ],
        ),
    ]
