# Generated by Django 4.0.1 on 2022-02-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_contract_date_updated_alter_event_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payement_due',
            field=models.DateField(),
        ),
    ]
