# Generated by Django 4.0.1 on 2022-02-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'manager'), ('sales', 'sales'), ('support', 'support')], default='support', max_length=16),
        ),
    ]
